/// Blasons pré-vérifiés des grands clubs (généré, URLs stables ESPN/API-Sports).
/// Zéro réseau : affichage instantané. La recherche dynamique ne sert
/// que pour les équipes hors liste.
const kSeedTeamBadges = <String, String>{
  'ac milan': 'https://a.espncdn.com/i/teamlogos/soccer/500/103.png',
  'ajax': 'https://media.api-sports.io/football/teams/194.png',
  'alaves': 'https://media.api-sports.io/football/teams/17168.png',
  'albacete': 'https://a.espncdn.com/i/teamlogos/soccer/500/2737.png',
  'angers': 'https://a.espncdn.com/i/teamlogos/soccer/500/7868.png',
  'arsenal': 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png',
  'atalanta': 'https://a.espncdn.com/i/teamlogos/soccer/500/105.png',
  'athletic bilbao': 'https://a.espncdn.com/i/teamlogos/soccer/500/93.png',
  'athletic club': 'https://media.api-sports.io/football/teams/13975.png',
  'atletico madrid': 'https://a.espncdn.com/i/teamlogos/soccer/500/1068.png',
  'augsburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/3841.png',
  'auxerre': 'https://a.espncdn.com/i/teamlogos/soccer/500/172.png',
  'barcelona': 'https://a.espncdn.com/i/teamlogos/soccer/500/83.png',
  'bayern munich': 'https://a.espncdn.com/i/teamlogos/soccer/500/132.png',
  'benfica': 'https://media.api-sports.io/football/teams/211.png',
  'besiktas': 'https://media.api-sports.io/football/teams/549.png',
  'betis': 'https://media.api-sports.io/football/teams/1907.png',
  'bochum': 'https://a.espncdn.com/i/teamlogos/soccer/500/121.png',
  'bologna': 'https://a.espncdn.com/i/teamlogos/soccer/500/107.png',
  'borussia dortmund': 'https://a.espncdn.com/i/teamlogos/soccer/500/124.png',
  'bournemouth': 'https://a.espncdn.com/i/teamlogos/soccer/500/349.png',
  'brentford': 'https://a.espncdn.com/i/teamlogos/soccer/500/337.png',
  'brest': 'https://a.espncdn.com/i/teamlogos/soccer/500/6997.png',
  'brighton': 'https://media.api-sports.io/football/teams/1857.png',
  'burnley': 'https://a.espncdn.com/i/teamlogos/soccer/500/379.png',
  'cagliari': 'https://a.espncdn.com/i/teamlogos/soccer/500/2925.png',
  'celta vigo': 'https://a.espncdn.com/i/teamlogos/soccer/500/85.png',
  'celtic': 'https://a.espncdn.com/i/teamlogos/soccer/500/256.png',
  'chelsea': 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png',
  'como': 'https://a.espncdn.com/i/teamlogos/soccer/500/2572.png',
  'crystal palace': 'https://a.espncdn.com/i/teamlogos/soccer/500/384.png',
  'dortmund': 'https://media.api-sports.io/football/teams/12726.png',
  'ein frankfurt': 'https://a.espncdn.com/i/teamlogos/soccer/500/125.png',
  'empoli': 'https://a.espncdn.com/i/teamlogos/soccer/500/2574.png',
  'espanyol': 'https://a.espncdn.com/i/teamlogos/soccer/500/88.png',
  'everton': 'https://a.espncdn.com/i/teamlogos/soccer/500/368.png',
  'fenerbahce': 'https://media.api-sports.io/football/teams/611.png',
  'feyenoord': 'https://media.api-sports.io/football/teams/209.png',
  'fiorentina': 'https://a.espncdn.com/i/teamlogos/soccer/500/109.png',
  'freiburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/126.png',
  'fulham': 'https://a.espncdn.com/i/teamlogos/soccer/500/370.png',
  'galatasaray': 'https://media.api-sports.io/football/teams/645.png',
  'genoa': 'https://a.espncdn.com/i/teamlogos/soccer/500/3263.png',
  'getafe': 'https://a.espncdn.com/i/teamlogos/soccer/500/2922.png',
  'girona': 'https://a.espncdn.com/i/teamlogos/soccer/500/9812.png',
  'gladbach': 'https://media.api-sports.io/football/teams/9366.png',
  'heidenheim': 'https://a.espncdn.com/i/teamlogos/soccer/500/6418.png',
  'hoffenheim': 'https://a.espncdn.com/i/teamlogos/soccer/500/7911.png',
  'holstein kiel': 'https://a.espncdn.com/i/teamlogos/soccer/500/7884.png',
  'inter': 'https://media.api-sports.io/football/teams/8160.png',
  'juventus': 'https://a.espncdn.com/i/teamlogos/soccer/500/111.png',
  'las palmas': 'https://a.espncdn.com/i/teamlogos/soccer/500/98.png',
  'lazio': 'https://a.espncdn.com/i/teamlogos/soccer/500/112.png',
  'le havre': 'https://a.espncdn.com/i/teamlogos/soccer/500/3236.png',
  'lecce': 'https://a.espncdn.com/i/teamlogos/soccer/500/113.png',
  'leeds united': 'https://a.espncdn.com/i/teamlogos/soccer/500/357.png',
  'leganes': 'https://a.espncdn.com/i/teamlogos/soccer/500/17534.png',
  'leicester': 'https://media.api-sports.io/football/teams/7195.png',
  'lens': 'https://a.espncdn.com/i/teamlogos/soccer/500/175.png',
  'leverkusen': 'https://a.espncdn.com/i/teamlogos/soccer/500/131.png',
  'liverpool': 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png',
  'lyon': 'https://a.espncdn.com/i/teamlogos/soccer/500/167.png',
  'm laga': 'https://a.espncdn.com/i/teamlogos/soccer/500/99.png',
  'mainz': 'https://a.espncdn.com/i/teamlogos/soccer/500/2950.png',
  'malaga': 'https://a.espncdn.com/i/teamlogos/soccer/500/99.png',
  'mallorca': 'https://a.espncdn.com/i/teamlogos/soccer/500/84.png',
  'man city': 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png',
  'man united': 'https://media.api-sports.io/football/teams/3767.png',
  'manchester city': 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png',
  'manchester united': 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png',
  'marseille': 'https://a.espncdn.com/i/teamlogos/soccer/500/176.png',
  'milan': 'https://media.api-sports.io/football/teams/15670.png',
  'monaco': 'https://a.espncdn.com/i/teamlogos/soccer/500/174.png',
  'montpellier': 'https://a.espncdn.com/i/teamlogos/soccer/500/274.png',
  'monza': 'https://a.espncdn.com/i/teamlogos/soccer/500/4007.png',
  'nantes': 'https://a.espncdn.com/i/teamlogos/soccer/500/165.png',
  'napoli': 'https://a.espncdn.com/i/teamlogos/soccer/500/114.png',
  'nice': 'https://a.espncdn.com/i/teamlogos/soccer/500/2502.png',
  'osasuna': 'https://a.espncdn.com/i/teamlogos/soccer/500/97.png',
  'parma': 'https://a.espncdn.com/i/teamlogos/soccer/500/115.png',
  'porto': 'https://media.api-sports.io/football/teams/212.png',
  'psv': 'https://media.api-sports.io/football/teams/197.png',
  'rangers': 'https://a.espncdn.com/i/teamlogos/soccer/500/257.png',
  'rayo vallecano': 'https://a.espncdn.com/i/teamlogos/soccer/500/101.png',
  'rb leipzig': 'https://a.espncdn.com/i/teamlogos/soccer/500/11420.png',
  'real madrid': 'https://a.espncdn.com/i/teamlogos/soccer/500/86.png',
  'real sociedad': 'https://a.espncdn.com/i/teamlogos/soccer/500/89.png',
  'reims': 'https://media.api-sports.io/football/teams/975.png',
  'rennes': 'https://a.espncdn.com/i/teamlogos/soccer/500/169.png',
  'roma': 'https://a.espncdn.com/i/teamlogos/soccer/500/104.png',
  'sevilla': 'https://a.espncdn.com/i/teamlogos/soccer/500/243.png',
  'southampton': 'https://a.espncdn.com/i/teamlogos/soccer/500/376.png',
  'sporting cp': 'https://media.api-sports.io/football/teams/228.png',
  'st etienne': 'https://a.espncdn.com/i/teamlogos/soccer/500/178.png',
  'st pauli': 'https://a.espncdn.com/i/teamlogos/soccer/500/270.png',
  'strasbourg': 'https://a.espncdn.com/i/teamlogos/soccer/500/180.png',
  'stuttgart': 'https://a.espncdn.com/i/teamlogos/soccer/500/134.png',
  'sunderland': 'https://a.espncdn.com/i/teamlogos/soccer/500/366.png',
  'torino': 'https://a.espncdn.com/i/teamlogos/soccer/500/239.png',
  'tottenham': 'https://media.api-sports.io/football/teams/4899.png',
  'toulouse': 'https://a.espncdn.com/i/teamlogos/soccer/500/179.png',
  'udinese': 'https://a.espncdn.com/i/teamlogos/soccer/500/118.png',
  'union berlin': 'https://a.espncdn.com/i/teamlogos/soccer/500/598.png',
  'valencia': 'https://a.espncdn.com/i/teamlogos/soccer/500/94.png',
  'valladolid': 'https://media.api-sports.io/football/teams/333.png',
  'venezia': 'https://a.espncdn.com/i/teamlogos/soccer/500/17530.png',
  'verona': 'https://media.api-sports.io/football/teams/1883.png',
  'villarreal': 'https://a.espncdn.com/i/teamlogos/soccer/500/102.png',
  'werder bremen': 'https://a.espncdn.com/i/teamlogos/soccer/500/137.png',
  'west ham': 'https://media.api-sports.io/football/teams/1856.png',
  'wolfsburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/138.png',
  'wolves': 'https://media.api-sports.io/football/teams/25133.png',
  'aston villa': 'https://a.espncdn.com/i/teamlogos/soccer/500/362.png',
  'newcastle': 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png',
  'newcastle united': 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png',
  'paris saint germain': 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png',
  'psg': 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png',
  'saint etienne': 'https://a.espncdn.com/i/teamlogos/soccer/500/178.png',
  'aberdeen': 'https://a.espncdn.com/i/teamlogos/soccer/500/263.png',
  'aek athens': 'https://media.api-sports.io/football/teams/575.png',
  'aik': 'https://media.api-sports.io/football/teams/377.png',
  'ajaccio': 'https://a.espncdn.com/i/teamlogos/soccer/500/2503.png',
  'al ahli saudi': 'https://media.api-sports.io/football/teams/2929.png',
  'al ahly': 'https://media.api-sports.io/football/teams/1577.png',
  'al duhail': 'https://media.api-sports.io/football/teams/2904.png',
  'al ettifaq': 'https://media.api-sports.io/football/teams/2934.png',
  'al hilal': 'https://media.api-sports.io/football/teams/19868.png',
  'al ittihad': 'https://media.api-sports.io/football/teams/1043.png',
  'al nassr': 'https://media.api-sports.io/football/teams/2939.png',
  'al rayyan': 'https://media.api-sports.io/football/teams/2897.png',
  'al sadd': 'https://media.api-sports.io/football/teams/2895.png',
  'almeria': 'https://a.espncdn.com/i/teamlogos/soccer/500/6832.png',
  'amiens': 'https://a.espncdn.com/i/teamlogos/soccer/500/3335.png',
  'anderlecht': 'https://media.api-sports.io/football/teams/554.png',
  'annecy': 'https://a.espncdn.com/i/teamlogos/soccer/500/18066.png',
  'antalyaspor': 'https://media.api-sports.io/football/teams/1005.png',
  'antwerp': 'https://media.api-sports.io/football/teams/740.png',
  'apoel': 'https://media.api-sports.io/football/teams/1391.png',
  'arouca': 'https://media.api-sports.io/football/teams/240.png',
  'athletico paranaense': 'https://a.espncdn.com/i/teamlogos/soccer/500/3458.png',
  'atlanta united': 'https://a.espncdn.com/i/teamlogos/soccer/500/18418.png',
  'atletico mineiro': 'https://media.api-sports.io/football/teams/1062.png',
  'austria wien': 'https://media.api-sports.io/football/teams/17575.png',
  'az alkmaar': 'https://media.api-sports.io/football/teams/201.png',
  'bahia': 'https://media.api-sports.io/football/teams/118.png',
  'bari': 'https://a.espncdn.com/i/teamlogos/soccer/500/106.png',
  'basaksehir': 'https://media.api-sports.io/football/teams/564.png',
  'basel': 'https://media.api-sports.io/football/teams/551.png',
  'bastia': 'https://a.espncdn.com/i/teamlogos/soccer/500/173.png',
  'birmingham city': 'https://a.espncdn.com/i/teamlogos/soccer/500/392.png',
  'blackburn rovers': 'https://a.espncdn.com/i/teamlogos/soccer/500/365.png',
  'boavista': 'https://media.api-sports.io/football/teams/222.png',
  'bodo glimt': 'https://media.api-sports.io/football/teams/327.png',
  'borussia monchengladbach': 'https://a.espncdn.com/i/teamlogos/soccer/500/268.png',
  'botafogo': 'https://media.api-sports.io/football/teams/120.png',
  'braga': 'https://media.api-sports.io/football/teams/217.png',
  'brann': 'https://media.api-sports.io/football/teams/319.png',
  'brescia': 'https://a.espncdn.com/i/teamlogos/soccer/500/108.png',
  'bristol city': 'https://a.espncdn.com/i/teamlogos/soccer/500/333.png',
  'brondby': 'https://media.api-sports.io/football/teams/407.png',
  'burgos': 'https://a.espncdn.com/i/teamlogos/soccer/500/12597.png',
  'cadiz': 'https://a.espncdn.com/i/teamlogos/soccer/500/3842.png',
  'caen': 'https://a.espncdn.com/i/teamlogos/soccer/500/2927.png',
  'cardiff city': 'https://a.espncdn.com/i/teamlogos/soccer/500/347.png',
  'cartagena': 'https://a.espncdn.com/i/teamlogos/soccer/500/5419.png',
  'casa pia': 'https://media.api-sports.io/football/teams/4716.png',
  'castellon': 'https://a.espncdn.com/i/teamlogos/soccer/500/4438.png',
  'catanzaro': 'https://a.espncdn.com/i/teamlogos/soccer/500/3257.png',
  'cercle brugge': 'https://media.api-sports.io/football/teams/741.png',
  'cesena': 'https://a.espncdn.com/i/teamlogos/soccer/500/3337.png',
  'cfr cluj': 'https://media.api-sports.io/football/teams/2246.png',
  'charleroi': 'https://media.api-sports.io/football/teams/736.png',
  'chivas guadalajara': 'https://a.espncdn.com/i/teamlogos/soccer/500/219.png',
  'cittadella': 'https://a.espncdn.com/i/teamlogos/soccer/500/3943.png',
  'clermont foot': 'https://a.espncdn.com/i/teamlogos/soccer/500/3171.png',
  'club africain': 'https://media.api-sports.io/football/teams/988.png',
  'club america': 'https://a.espncdn.com/i/teamlogos/soccer/500/227.png',
  'club brugge': 'https://media.api-sports.io/football/teams/569.png',
  'columbus crew': 'https://a.espncdn.com/i/teamlogos/soccer/500/183.png',
  'corinthians': 'https://media.api-sports.io/football/teams/131.png',
  'cosenza': 'https://a.espncdn.com/i/teamlogos/soccer/500/8683.png',
  'coventry city': 'https://a.espncdn.com/i/teamlogos/soccer/500/388.png',
  'cr belouizdad': 'https://media.api-sports.io/football/teams/904.png',
  'cremonese': 'https://a.espncdn.com/i/teamlogos/soccer/500/4050.png',
  'cruz azul': 'https://a.espncdn.com/i/teamlogos/soccer/500/218.png',
  'cruzeiro': 'https://media.api-sports.io/football/teams/135.png',
  'darmstadt': 'https://a.espncdn.com/i/teamlogos/soccer/500/3812.png',
  'deportivo la coruna': 'https://media.api-sports.io/football/teams/9610.png',
  'derby county': 'https://a.espncdn.com/i/teamlogos/soccer/500/374.png',
  'dinamo zagreb': 'https://media.api-sports.io/football/teams/620.png',
  'djurgarden': 'https://media.api-sports.io/football/teams/364.png',
  'dunkerque': 'https://a.espncdn.com/i/teamlogos/soccer/500/7732.png',
  'dusseldorf': 'https://media.api-sports.io/football/teams/246.png',
  'dynamo kyiv': 'https://media.api-sports.io/football/teams/572.png',
  'eibar': 'https://a.espncdn.com/i/teamlogos/soccer/500/3752.png',
  'eintracht frankfurt': 'https://a.espncdn.com/i/teamlogos/soccer/500/125.png',
  'elche': 'https://a.espncdn.com/i/teamlogos/soccer/500/3751.png',
  'elversberg': 'https://a.espncdn.com/i/teamlogos/soccer/500/10388.png',
  'esperance de tunis': 'https://media.api-sports.io/football/teams/980.png',
  'estoril': 'https://media.api-sports.io/football/teams/230.png',
  'estrela amadora': 'https://media.api-sports.io/football/teams/15130.png',
  'estudiantes': 'https://media.api-sports.io/football/teams/284.png',
  'etoile du sahel': 'https://media.api-sports.io/football/teams/990.png',
  'famalicao': 'https://media.api-sports.io/football/teams/242.png',
  'far rabat': 'https://media.api-sports.io/football/teams/969.png',
  'farense': 'https://media.api-sports.io/football/teams/231.png',
  'fc copenhagen': 'https://media.api-sports.io/football/teams/400.png',
  'fcsb': 'https://media.api-sports.io/football/teams/559.png',
  'ferencvaros': 'https://media.api-sports.io/football/teams/651.png',
  'flamengo': 'https://media.api-sports.io/football/teams/127.png',
  'fluminense': 'https://media.api-sports.io/football/teams/124.png',
  'fortaleza': 'https://media.api-sports.io/football/teams/154.png',
  'fortuna sittard': 'https://media.api-sports.io/football/teams/205.png',
  'frosinone': 'https://a.espncdn.com/i/teamlogos/soccer/500/4057.png',
  'genk': 'https://media.api-sports.io/football/teams/742.png',
  'gent': 'https://media.api-sports.io/football/teams/631.png',
  'gil vicente': 'https://media.api-sports.io/football/teams/762.png',
  'go ahead eagles': 'https://media.api-sports.io/football/teams/410.png',
  'gremio': 'https://a.espncdn.com/i/teamlogos/soccer/500/6273.png',
  'grenoble': 'https://a.espncdn.com/i/teamlogos/soccer/500/6994.png',
  'greuther furth': 'https://a.espncdn.com/i/teamlogos/soccer/500/3070.png',
  'groningen': 'https://media.api-sports.io/football/teams/202.png',
  'guingamp': 'https://a.espncdn.com/i/teamlogos/soccer/500/171.png',
  'hajduk split': 'https://media.api-sports.io/football/teams/608.png',
  'hamburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/127.png',
  'hammarby': 'https://media.api-sports.io/football/teams/363.png',
  'hannover 96': 'https://a.espncdn.com/i/teamlogos/soccer/500/2428.png',
  'hearts': 'https://media.api-sports.io/football/teams/12249.png',
  'heerenveen': 'https://media.api-sports.io/football/teams/210.png',
  'heracles': 'https://media.api-sports.io/football/teams/206.png',
  'hertha berlin': 'https://media.api-sports.io/football/teams/27444.png',
  'hibernian': 'https://a.espncdn.com/i/teamlogos/soccer/500/258.png',
  'huesca': 'https://a.espncdn.com/i/teamlogos/soccer/500/5413.png',
  'hull city': 'https://a.espncdn.com/i/teamlogos/soccer/500/306.png',
  'independiente': 'https://media.api-sports.io/football/teams/453.png',
  'inter miami': 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png',
  'internacional': 'https://media.api-sports.io/football/teams/119.png',
  'jagiellonia': 'https://media.api-sports.io/football/teams/336.png',
  'jahn regensburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/11017.png',
  'js kabylie': 'https://media.api-sports.io/football/teams/918.png',
  'kaiserslautern': 'https://a.espncdn.com/i/teamlogos/soccer/500/130.png',
  'kaizer chiefs': 'https://media.api-sports.io/football/teams/2691.png',
  'karlsruhe': 'https://a.espncdn.com/i/teamlogos/soccer/500/4471.png',
  'kashima antlers': 'https://media.api-sports.io/football/teams/290.png',
  'koln': 'https://a.espncdn.com/i/teamlogos/soccer/500/122.png',
  'konyaspor': 'https://media.api-sports.io/football/teams/607.png',
  'la galaxy': 'https://a.espncdn.com/i/teamlogos/soccer/500/187.png',
  'lafc': 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png',
  'lanus': 'https://media.api-sports.io/football/teams/446.png',
  'laval': 'https://a.espncdn.com/i/teamlogos/soccer/500/3266.png',
  'lech poznan': 'https://media.api-sports.io/football/teams/347.png',
  'legia warsaw': 'https://media.api-sports.io/football/teams/339.png',
  'leon': 'https://a.espncdn.com/i/teamlogos/soccer/500/228.png',
  'levante': 'https://a.espncdn.com/i/teamlogos/soccer/500/1538.png',
  'lorient': 'https://a.espncdn.com/i/teamlogos/soccer/500/273.png',
  'lugano': 'https://media.api-sports.io/football/teams/606.png',
  'luton town': 'https://a.espncdn.com/i/teamlogos/soccer/500/301.png',
  'maccabi haifa': 'https://media.api-sports.io/football/teams/4195.png',
  'maccabi tel aviv': 'https://media.api-sports.io/football/teams/604.png',
  'magdeburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/9867.png',
  'malmo ff': 'https://media.api-sports.io/football/teams/21698.png',
  'mamelodi sundowns': 'https://media.api-sports.io/football/teams/2699.png',
  'mantova': 'https://a.espncdn.com/i/teamlogos/soccer/500/3991.png',
  'martigues': 'https://a.espncdn.com/i/teamlogos/soccer/500/11312.png',
  'mc alger': 'https://media.api-sports.io/football/teams/906.png',
  'mechelen': 'https://media.api-sports.io/football/teams/266.png',
  'metz': 'https://a.espncdn.com/i/teamlogos/soccer/500/177.png',
  'middlesbrough': 'https://a.espncdn.com/i/teamlogos/soccer/500/369.png',
  'midtjylland': 'https://media.api-sports.io/football/teams/26101.png',
  'millwall': 'https://a.espncdn.com/i/teamlogos/soccer/500/391.png',
  'mirandes': 'https://a.espncdn.com/i/teamlogos/soccer/500/4515.png',
  'modena': 'https://a.espncdn.com/i/teamlogos/soccer/500/2573.png',
  'molde': 'https://media.api-sports.io/football/teams/329.png',
  'monterrey': 'https://a.espncdn.com/i/teamlogos/soccer/500/220.png',
  'moreirense': 'https://media.api-sports.io/football/teams/215.png',
  'nac breda': 'https://media.api-sports.io/football/teams/203.png',
  'nacional madeira': 'https://media.api-sports.io/football/teams/225.png',
  'nec nijmegen': 'https://media.api-sports.io/football/teams/413.png',
  'new york city fc': 'https://a.espncdn.com/i/teamlogos/soccer/500/17606.png',
  'new york red bulls': 'https://a.espncdn.com/i/teamlogos/soccer/500/190.png',
  'newell s old boys': 'https://media.api-sports.io/football/teams/457.png',
  'nordsjaelland': 'https://media.api-sports.io/football/teams/398.png',
  'norwich city': 'https://a.espncdn.com/i/teamlogos/soccer/500/381.png',
  'nurnberg': 'https://a.espncdn.com/i/teamlogos/soccer/500/269.png',
  'olympiacos': 'https://media.api-sports.io/football/teams/553.png',
  'omonia nicosia': 'https://media.api-sports.io/football/teams/3402.png',
  'orlando pirates': 'https://media.api-sports.io/football/teams/2700.png',
  'oviedo': 'https://media.api-sports.io/football/teams/1131.png',
  'oxford united': 'https://a.espncdn.com/i/teamlogos/soccer/500/311.png',
  'pachuca': 'https://a.espncdn.com/i/teamlogos/soccer/500/234.png',
  'paderborn': 'https://a.espncdn.com/i/teamlogos/soccer/500/3307.png',
  'palermo': 'https://a.espncdn.com/i/teamlogos/soccer/500/2923.png',
  'palmeiras': 'https://media.api-sports.io/football/teams/121.png',
  'panathinaikos': 'https://media.api-sports.io/football/teams/617.png',
  'paok': 'https://media.api-sports.io/football/teams/619.png',
  'paris fc': 'https://a.espncdn.com/i/teamlogos/soccer/500/6851.png',
  'partizan belgrade': 'https://media.api-sports.io/football/teams/573.png',
  'pau fc': 'https://a.espncdn.com/i/teamlogos/soccer/500/10678.png',
  'pisa': 'https://a.espncdn.com/i/teamlogos/soccer/500/3956.png',
  'plymouth argyle': 'https://a.espncdn.com/i/teamlogos/soccer/500/307.png',
  'portland timbers': 'https://a.espncdn.com/i/teamlogos/soccer/500/9723.png',
  'portsmouth': 'https://a.espncdn.com/i/teamlogos/soccer/500/385.png',
  'preston north end': 'https://a.espncdn.com/i/teamlogos/soccer/500/394.png',
  'preussen munster': 'https://a.espncdn.com/i/teamlogos/soccer/500/9867.png',
  'psv eindhoven': 'https://media.api-sports.io/football/teams/197.png',
  'pumas unam': 'https://a.espncdn.com/i/teamlogos/soccer/500/233.png',
  'pyramids fc': 'https://media.api-sports.io/football/teams/1036.png',
  'qpr': 'https://a.espncdn.com/i/teamlogos/soccer/500/334.png',
  'racing club': 'https://media.api-sports.io/football/teams/436.png',
  'racing ferrol': 'https://a.espncdn.com/i/teamlogos/soccer/500/8448.png',
  'racing santander': 'https://a.espncdn.com/i/teamlogos/soccer/500/87.png',
  'raja casablanca': 'https://media.api-sports.io/football/teams/976.png',
  'rapid wien': 'https://media.api-sports.io/football/teams/8247.png',
  'real betis': 'https://a.espncdn.com/i/teamlogos/soccer/500/244.png',
  'red star belgrade': 'https://media.api-sports.io/football/teams/598.png',
  'red star': 'https://a.espncdn.com/i/teamlogos/soccer/500/11884.png',
  'reggiana': 'https://a.espncdn.com/i/teamlogos/soccer/500/3942.png',
  'rijeka': 'https://media.api-sports.io/football/teams/561.png',
  'rio ave': 'https://media.api-sports.io/football/teams/226.png',
  'river plate': 'https://a.espncdn.com/i/teamlogos/soccer/500/16.png',
  'rizespor': 'https://media.api-sports.io/football/teams/1007.png',
  'rodez': 'https://a.espncdn.com/i/teamlogos/soccer/500/7719.png',
  'rosario central': 'https://media.api-sports.io/football/teams/437.png',
  'rosenborg': 'https://media.api-sports.io/football/teams/331.png',
  'rs berkane': 'https://media.api-sports.io/football/teams/962.png',
  'salernitana': 'https://a.espncdn.com/i/teamlogos/soccer/500/3240.png',
  'salzburg': 'https://media.api-sports.io/football/teams/7928.png',
  'sampdoria': 'https://a.espncdn.com/i/teamlogos/soccer/500/2734.png',
  'samsunspor': 'https://media.api-sports.io/football/teams/3603.png',
  'san lorenzo': 'https://media.api-sports.io/football/teams/460.png',
  'santa clara': 'https://media.api-sports.io/football/teams/227.png',
  'santos laguna': 'https://a.espncdn.com/i/teamlogos/soccer/500/225.png',
  'santos': 'https://media.api-sports.io/football/teams/128.png',
  'sao paulo': 'https://media.api-sports.io/football/teams/126.png',
  'sassuolo': 'https://a.espncdn.com/i/teamlogos/soccer/500/3997.png',
  'schalke 04': 'https://a.espncdn.com/i/teamlogos/soccer/500/133.png',
  'seattle sounders': 'https://a.espncdn.com/i/teamlogos/soccer/500/9726.png',
  'servette': 'https://media.api-sports.io/football/teams/2184.png',
  'shakhtar donetsk': 'https://media.api-sports.io/football/teams/550.png',
  'sheffield united': 'https://a.espncdn.com/i/teamlogos/soccer/500/398.png',
  'sheffield wednesday': 'https://a.espncdn.com/i/teamlogos/soccer/500/399.png',
  'slavia prague': 'https://media.api-sports.io/football/teams/560.png',
  'sparta prague': 'https://media.api-sports.io/football/teams/628.png',
  'sparta rotterdam': 'https://media.api-sports.io/football/teams/426.png',
  'spezia': 'https://a.espncdn.com/i/teamlogos/soccer/500/4056.png',
  'sporting gijon': 'https://media.api-sports.io/football/teams/9577.png',
  'sporting': 'https://media.api-sports.io/football/teams/228.png',
  'st gallen': 'https://media.api-sports.io/football/teams/10587.png',
  'standard liege': 'https://media.api-sports.io/football/teams/733.png',
  'stoke city': 'https://a.espncdn.com/i/teamlogos/soccer/500/336.png',
  'sturm graz': 'https://media.api-sports.io/football/teams/637.png',
  'sudtirol': 'https://a.espncdn.com/i/teamlogos/soccer/500/11139.png',
  'swansea city': 'https://a.espncdn.com/i/teamlogos/soccer/500/318.png',
  'tenerife': 'https://a.espncdn.com/i/teamlogos/soccer/500/245.png',
  'tigres uanl': 'https://a.espncdn.com/i/teamlogos/soccer/500/232.png',
  'toluca': 'https://a.espncdn.com/i/teamlogos/soccer/500/223.png',
  'toronto fc': 'https://media.api-sports.io/football/teams/1601.png',
  'tp mazembe': 'https://media.api-sports.io/football/teams/6435.png',
  'trabzonspor': 'https://media.api-sports.io/football/teams/998.png',
  'troyes': 'https://a.espncdn.com/i/teamlogos/soccer/500/170.png',
  'twente': 'https://media.api-sports.io/football/teams/415.png',
  'ulm': 'https://media.api-sports.io/football/teams/533.png',
  'urawa red diamonds': 'https://media.api-sports.io/football/teams/287.png',
  'usm alger': 'https://media.api-sports.io/football/teams/910.png',
  'utrecht': 'https://media.api-sports.io/football/teams/207.png',
  'vasco da gama': 'https://media.api-sports.io/football/teams/133.png',
  'velez sarsfield': 'https://media.api-sports.io/football/teams/438.png',
  'viktoria plzen': 'https://media.api-sports.io/football/teams/567.png',
  'vissel kobe': 'https://media.api-sports.io/football/teams/289.png',
  'vitesse': 'https://media.api-sports.io/football/teams/200.png',
  'vitoria guimaraes': 'https://media.api-sports.io/football/teams/224.png',
  'watford': 'https://a.espncdn.com/i/teamlogos/soccer/500/395.png',
  'west brom': 'https://media.api-sports.io/football/teams/11913.png',
  'willem ii': 'https://media.api-sports.io/football/teams/195.png',
  'wisla krakow': 'https://media.api-sports.io/football/teams/338.png',
  'wydad ac': 'https://media.api-sports.io/football/teams/3459.png',
  'young boys': 'https://media.api-sports.io/football/teams/565.png',
  'zamalek': 'https://media.api-sports.io/football/teams/1040.png',
  'zaragoza': 'https://media.api-sports.io/football/teams/1917.png',
};
