/// Blasons pré-vérifiés des grands clubs (généré, URLs stables ESPN/API-Sports).
/// Zéro réseau : affichage instantané. La recherche dynamique ne sert
/// que pour les équipes hors liste.
const kSeedTeamBadges = <String, String>{
  'ac milan': 'https://a.espncdn.com/i/teamlogos/soccer/500/103.png',
  'ajax': 'https://media.api-sports.io/football/teams/194.png',
  'alaves': 'https://media.api-sports.io/football/teams/17168.png',
  'albacete': 'https://a.espncdn.com/i/teamlogos/soccer/500/2737.png',
  'angers': 'https://a.espncdn.com/i/teamlogos/soccer/500/7868.png',
  'arsenal': 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png',
  'atalanta': 'https://a.espncdn.com/i/teamlogos/soccer/500/105.png',
  'athletic bilbao': 'https://a.espncdn.com/i/teamlogos/soccer/500/93.png',
  'athletic club': 'https://media.api-sports.io/football/teams/13975.png',
  'atletico madrid': 'https://a.espncdn.com/i/teamlogos/soccer/500/1068.png',
  'augsburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/3841.png',
  'auxerre': 'https://a.espncdn.com/i/teamlogos/soccer/500/172.png',
  'barcelona': 'https://a.espncdn.com/i/teamlogos/soccer/500/83.png',
  'bayern munich': 'https://a.espncdn.com/i/teamlogos/soccer/500/132.png',
  'benfica': 'https://media.api-sports.io/football/teams/211.png',
  'besiktas': 'https://media.api-sports.io/football/teams/549.png',
  'betis': 'https://media.api-sports.io/football/teams/1907.png',
  'bochum': 'https://a.espncdn.com/i/teamlogos/soccer/500/121.png',
  'bologna': 'https://a.espncdn.com/i/teamlogos/soccer/500/107.png',
  'borussia dortmund': 'https://a.espncdn.com/i/teamlogos/soccer/500/124.png',
  'bournemouth': 'https://a.espncdn.com/i/teamlogos/soccer/500/349.png',
  'brentford': 'https://a.espncdn.com/i/teamlogos/soccer/500/337.png',
  'brest': 'https://a.espncdn.com/i/teamlogos/soccer/500/6997.png',
  'brighton': 'https://media.api-sports.io/football/teams/1857.png',
  'burnley': 'https://a.espncdn.com/i/teamlogos/soccer/500/379.png',
  'cagliari': 'https://a.espncdn.com/i/teamlogos/soccer/500/2925.png',
  'celta vigo': 'https://a.espncdn.com/i/teamlogos/soccer/500/85.png',
  'celtic': 'https://a.espncdn.com/i/teamlogos/soccer/500/256.png',
  'chelsea': 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png',
  'como': 'https://a.espncdn.com/i/teamlogos/soccer/500/2572.png',
  'crystal palace': 'https://a.espncdn.com/i/teamlogos/soccer/500/384.png',
  'dortmund': 'https://media.api-sports.io/football/teams/12726.png',
  'ein frankfurt': 'https://a.espncdn.com/i/teamlogos/soccer/500/125.png',
  'empoli': 'https://a.espncdn.com/i/teamlogos/soccer/500/2574.png',
  'espanyol': 'https://a.espncdn.com/i/teamlogos/soccer/500/88.png',
  'everton': 'https://a.espncdn.com/i/teamlogos/soccer/500/368.png',
  'fenerbahce': 'https://media.api-sports.io/football/teams/611.png',
  'feyenoord': 'https://media.api-sports.io/football/teams/209.png',
  'fiorentina': 'https://a.espncdn.com/i/teamlogos/soccer/500/109.png',
  'freiburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/126.png',
  'fulham': 'https://a.espncdn.com/i/teamlogos/soccer/500/370.png',
  'galatasaray': 'https://media.api-sports.io/football/teams/645.png',
  'genoa': 'https://a.espncdn.com/i/teamlogos/soccer/500/3263.png',
  'getafe': 'https://a.espncdn.com/i/teamlogos/soccer/500/2922.png',
  'girona': 'https://a.espncdn.com/i/teamlogos/soccer/500/9812.png',
  'gladbach': 'https://media.api-sports.io/football/teams/9366.png',
  'heidenheim': 'https://a.espncdn.com/i/teamlogos/soccer/500/6418.png',
  'hoffenheim': 'https://a.espncdn.com/i/teamlogos/soccer/500/7911.png',
  'holstein kiel': 'https://a.espncdn.com/i/teamlogos/soccer/500/7884.png',
  'inter': 'https://media.api-sports.io/football/teams/8160.png',
  'juventus': 'https://a.espncdn.com/i/teamlogos/soccer/500/111.png',
  'las palmas': 'https://a.espncdn.com/i/teamlogos/soccer/500/98.png',
  'lazio': 'https://a.espncdn.com/i/teamlogos/soccer/500/112.png',
  'le havre': 'https://a.espncdn.com/i/teamlogos/soccer/500/3236.png',
  'lecce': 'https://a.espncdn.com/i/teamlogos/soccer/500/113.png',
  'leeds united': 'https://a.espncdn.com/i/teamlogos/soccer/500/357.png',
  'leganes': 'https://a.espncdn.com/i/teamlogos/soccer/500/17534.png',
  'leicester': 'https://media.api-sports.io/football/teams/7195.png',
  'lens': 'https://a.espncdn.com/i/teamlogos/soccer/500/175.png',
  'leverkusen': 'https://a.espncdn.com/i/teamlogos/soccer/500/131.png',
  'liverpool': 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png',
  'lyon': 'https://a.espncdn.com/i/teamlogos/soccer/500/167.png',
  'm laga': 'https://a.espncdn.com/i/teamlogos/soccer/500/99.png',
  'mainz': 'https://a.espncdn.com/i/teamlogos/soccer/500/2950.png',
  'malaga': 'https://a.espncdn.com/i/teamlogos/soccer/500/99.png',
  'mallorca': 'https://a.espncdn.com/i/teamlogos/soccer/500/84.png',
  'man city': 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png',
  'man united': 'https://media.api-sports.io/football/teams/3767.png',
  'manchester city': 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png',
  'manchester united': 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png',
  'marseille': 'https://a.espncdn.com/i/teamlogos/soccer/500/176.png',
  'milan': 'https://media.api-sports.io/football/teams/15670.png',
  'monaco': 'https://a.espncdn.com/i/teamlogos/soccer/500/174.png',
  'montpellier': 'https://a.espncdn.com/i/teamlogos/soccer/500/274.png',
  'monza': 'https://a.espncdn.com/i/teamlogos/soccer/500/4007.png',
  'nantes': 'https://a.espncdn.com/i/teamlogos/soccer/500/165.png',
  'napoli': 'https://a.espncdn.com/i/teamlogos/soccer/500/114.png',
  'nice': 'https://a.espncdn.com/i/teamlogos/soccer/500/2502.png',
  'osasuna': 'https://a.espncdn.com/i/teamlogos/soccer/500/97.png',
  'parma': 'https://a.espncdn.com/i/teamlogos/soccer/500/115.png',
  'porto': 'https://media.api-sports.io/football/teams/212.png',
  'psv': 'https://media.api-sports.io/football/teams/197.png',
  'rangers': 'https://a.espncdn.com/i/teamlogos/soccer/500/257.png',
  'rayo vallecano': 'https://a.espncdn.com/i/teamlogos/soccer/500/101.png',
  'rb leipzig': 'https://a.espncdn.com/i/teamlogos/soccer/500/11420.png',
  'real madrid': 'https://a.espncdn.com/i/teamlogos/soccer/500/86.png',
  'real sociedad': 'https://a.espncdn.com/i/teamlogos/soccer/500/89.png',
  'reims': 'https://media.api-sports.io/football/teams/975.png',
  'rennes': 'https://a.espncdn.com/i/teamlogos/soccer/500/169.png',
  'roma': 'https://a.espncdn.com/i/teamlogos/soccer/500/104.png',
  'sevilla': 'https://a.espncdn.com/i/teamlogos/soccer/500/243.png',
  'southampton': 'https://a.espncdn.com/i/teamlogos/soccer/500/376.png',
  'sporting cp': 'https://media.api-sports.io/football/teams/228.png',
  'st etienne': 'https://a.espncdn.com/i/teamlogos/soccer/500/178.png',
  'st pauli': 'https://a.espncdn.com/i/teamlogos/soccer/500/270.png',
  'strasbourg': 'https://a.espncdn.com/i/teamlogos/soccer/500/180.png',
  'stuttgart': 'https://a.espncdn.com/i/teamlogos/soccer/500/134.png',
  'sunderland': 'https://a.espncdn.com/i/teamlogos/soccer/500/366.png',
  'torino': 'https://a.espncdn.com/i/teamlogos/soccer/500/239.png',
  'tottenham': 'https://media.api-sports.io/football/teams/4899.png',
  'toulouse': 'https://a.espncdn.com/i/teamlogos/soccer/500/179.png',
  'udinese': 'https://a.espncdn.com/i/teamlogos/soccer/500/118.png',
  'union berlin': 'https://a.espncdn.com/i/teamlogos/soccer/500/598.png',
  'valencia': 'https://a.espncdn.com/i/teamlogos/soccer/500/94.png',
  'valladolid': 'https://media.api-sports.io/football/teams/333.png',
  'venezia': 'https://a.espncdn.com/i/teamlogos/soccer/500/17530.png',
  'verona': 'https://media.api-sports.io/football/teams/1883.png',
  'villarreal': 'https://a.espncdn.com/i/teamlogos/soccer/500/102.png',
  'werder bremen': 'https://a.espncdn.com/i/teamlogos/soccer/500/137.png',
  'west ham': 'https://media.api-sports.io/football/teams/1856.png',
  'wolfsburg': 'https://a.espncdn.com/i/teamlogos/soccer/500/138.png',
  'wolves': 'https://media.api-sports.io/football/teams/25133.png',
  'aston villa': 'https://a.espncdn.com/i/teamlogos/soccer/500/362.png',
  'newcastle': 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png',
  'newcastle united': 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png',
  'paris saint germain': 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png',
  'psg': 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png',
  'saint etienne': 'https://a.espncdn.com/i/teamlogos/soccer/500/178.png',
};
